### PR TITLE
Fill the repo with vscode extension prototype

### PR DESCRIPTION
**Pull request by tahini**

### CODE REVIEW

**Comment by bhufmann** [comment]
@tahini is there a way to change the default branch "main" to "master" as part of this patch or shall we do it afterwards?

**Comment by bhufmann** [comment]
> @tahini is there a way to change the default branch "main" to "master" as part of this patch or shall we do it afterwards?

I thought about it. Let's merge it and then we rename "main" to "master"

**Review by bhufmann — APPROVED** [review]

**Comment by tahini** [comment]
I don't have permissions on this repo, so I can't merge or rename, or do anything except do PRs ;-)

**Comment by bhufmann** [comment]
> I don't have permissions on this repo, so I can't merge or rename, or do anything except do PRs ;-)

Looking at the permissions, it looks like you haven't accepted the invite Marc sent out. I'll resent a new one.

**Pull request merged**
